title: m4rcix
url: https://m4rcix.github.io
author: m4rcix
email: 
description: > # this means to ignore newlines until "show_exerpts:"
  Page is under construction. There are leftover files from **https://bitbrain.github.io**
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: m4rcix-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/MarcixWasTaken
      icon: twitter-square
      color: cyan
    - url: https://www.twitch.tv/marcix
      icon: twitch
      color: purple
    - url: https://www.youtube.com/channel/UChaUSPtWwNkUpzrjUW7H0PA
      icon: youtube
      color: red
    - url: https://github.com/m4rcix
      icon: github-square
      color: yellow
    - url: https://www.linkedin.com/in/marton-bak-574a59201/
      icon: linkedin
      color: blue
    - url: https://app.hackthebox.eu/profile/367067
      icon: cube
      color: green
      fa: true
    - url: https://discord.com/invite/wGHG5Aj
      icon: discord
      color: blue

# Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging
  
avatar_source: github
github_username: m4rcix
